spring.application.name=Performance_prediction

# Disable DB + JPA completely
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

spring.thymeleaf.cache=false

server.port=${PORT:8080}
